# Generated by Django 4.1.2 on 2022-11-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Books",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book_title", models.CharField(max_length=200)),
                ("Author_name", models.CharField(max_length=200)),
                ("Genre", models.CharField(max_length=200)),
                ("Review", models.IntegerField()),
                ("Favorite", models.BooleanField(default=True)),
            ],
            options={"ordering": ["id"],},
        ),
    ]
