# Generated by Django 4.1.2 on 2022-11-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ebookapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="books", name="Favorite", field=models.BooleanField(),
        ),
    ]
